### ISSUE TITLE
Existing command 'SET_KINEMATIC_POSITION' not found in gcode_macro rename

### ISSUE THREAD

**Issue by astorun** [vladbabii/klipper.macro.g28_override#2]
It gives an error once I restart klipper. So I cannot use it.

Existing command 'SET_KINEMATIC_POSITION' not found in gcode_macro rename
Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

**Comment by robustini** [comment]
Same issue here.

**Comment by vladbabii** [comment]
Add this to your printer configuration
```
[force_move]
enable_force_move: true
```

**Comment by vladbabii** [comment]
Also update main doc. Thanks
